# Generated by Django 5.2.6 on 2025-10-26 03:02

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0004_librosolicitudesvistas'),
    ]

    operations = [
        migrations.CreateModel(
            name='Calificacion',
            fields=[
                ('id_clasificacion', models.AutoField(primary_key=True, serialize=False)),
                ('puntuacion', models.IntegerField()),
                ('comentario', models.TextField()),
            ],
            options={
                'db_table': 'calificacion',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Conversacion',
            fields=[
                ('id_conversacion', models.AutoField(primary_key=True, serialize=False)),
                ('creado_en', models.DateTimeField(default=django.utils.timezone.now)),
                ('actualizado_en', models.DateTimeField(default=django.utils.timezone.now)),
                ('ultimo_id_mensaje', models.IntegerField(db_column='ultimo_id_mensaje', default=0)),
            ],
            options={
                'db_table': 'conversacion',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ConversacionMensaje',
            fields=[
                ('id_mensaje', models.AutoField(db_column='id_mensaje', primary_key=True, serialize=False)),
                ('cuerpo', models.TextField(db_column='cuerpo')),
                ('enviado_en', models.DateTimeField(db_column='enviado_en')),
                ('editado_en', models.DateTimeField(blank=True, db_column='editado_en', null=True)),
                ('eliminado', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'conversacion_mensaje',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Genero',
            fields=[
                ('id_genero', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'genero',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='IntercambioCodigo',
            fields=[
                ('id_intercambio', models.OneToOneField(db_column='id_intercambio', on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='codigo', serialize=False, to='market.intercambio')),
                ('codigo', models.CharField(max_length=12, unique=True)),
                ('expira_en', models.DateTimeField(blank=True, null=True)),
                ('usado_en', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'intercambio_codigo',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SolicitudIntercambio',
            fields=[
                ('id_solicitud', models.AutoField(primary_key=True, serialize=False)),
                ('estado', models.CharField(choices=[('Pendiente', 'Pendiente'), ('Aceptada', 'Aceptada'), ('Rechazada', 'Rechazada'), ('Cancelada', 'Cancelada')], default='Pendiente', max_length=10)),
                ('lugar_intercambio', models.CharField(blank=True, max_length=255, null=True)),
                ('fecha_intercambio_pactada', models.DateTimeField(blank=True, null=True)),
                ('fecha_completado', models.DateTimeField(blank=True, null=True)),
                ('creada_en', models.DateTimeField(blank=True, null=True)),
                ('actualizada_en', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'solicitud_intercambio',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SolicitudOferta',
            fields=[
                ('id_oferta', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'solicitud_oferta',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='Clasificacion',
        ),
        migrations.CreateModel(
            name='ConversacionParticipante',
            fields=[
                ('id_conversacion', models.ForeignKey(db_column='id_conversacion', on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='participantes', serialize=False, to='market.conversacion')),
                ('rol', models.CharField(blank=True, max_length=20, null=True)),
                ('silenciado', models.BooleanField(default=False)),
                ('archivado', models.BooleanField(default=False)),
                ('ultimo_visto_id_mensaje', models.IntegerField(db_column='ultimo_visto_id_mensaje', default=0)),
                ('visto_en', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'conversacion_participante',
                'managed': False,
            },
        ),
    ]
