# Generated by Django 5.2.6 on 2025-11-01 01:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0005_calificacion_conversacion_conversacionmensaje_genero_and_more'),
    ]

    operations = [
    ]
