# Generated by Django 5.2.6 on 2025-11-01 01:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0006_merge_0006_conflict'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='conversacionparticipante',
            options={'managed': True},
        ),
    ]
