# Generated by Django 5.2.6 on 2025-11-05 04:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_passwordresettoken_options_and_more'),
        ('market', '0008_conv_part_pk_switch'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='conversacionparticipante',
            options={'managed': False},
        ),
        migrations.CreateModel(
            name='PuntoEncuentro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120)),
                ('tipo', models.CharField(choices=[('DUOC', 'DUOC'), ('BIBLIOTECA', 'Biblioteca'), ('CAMBIOTECA', 'Cambioteca'), ('METRO', 'Metro'), ('OTRO', 'Otro')], max_length=20)),
                ('place_id', models.CharField(blank=True, max_length=128, null=True)),
                ('latitud', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitud', models.DecimalField(decimal_places=6, max_digits=9)),
                ('direccion', models.CharField(blank=True, max_length=255, null=True)),
                ('habilitado', models.BooleanField(default=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'indexes': [models.Index(fields=['tipo', 'habilitado'], name='market_punt_tipo_f5f2c8_idx')],
            },
        ),
        migrations.CreateModel(
            name='PropuestaEncuentro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metodo', models.CharField(choices=[('MANUAL', 'Manual'), ('PREDEF', 'Predefinido')], max_length=10)),
                ('latitud', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitud', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('direccion', models.CharField(blank=True, max_length=255, null=True)),
                ('fecha_hora', models.DateTimeField()),
                ('notas', models.CharField(blank=True, max_length=240, null=True)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('ACEPTADA', 'Aceptada'), ('RECHAZADA', 'Rechazada')], default='PENDIENTE', max_length=10)),
                ('decidida_en', models.DateTimeField(blank=True, null=True)),
                ('activa', models.BooleanField(default=True)),
                ('creada_en', models.DateTimeField(auto_now_add=True)),
                ('decidida_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='propuestas_decididas', to='core.usuario')),
                ('id_intercambio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='propuestas', to='market.intercambio')),
                ('propuesta_por', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='propuestas_creadas', to='core.usuario')),
                ('id_punto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='propuestas', to='market.puntoencuentro')),
            ],
            options={
                'indexes': [models.Index(fields=['id_intercambio', 'estado'], name='market_prop_id_inte_979229_idx'), models.Index(fields=['id_intercambio', 'activa'], name='market_prop_id_inte_ffeb96_idx')],
            },
        ),
    ]
