# Generated by Django 5.2.6 on 2025-11-05 05:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0009_alter_conversacionparticipante_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='conversacionparticipante',
            options={'managed': True},
        ),
    ]
