# Generated by Django 5.2.6 on 2025-11-07 01:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0010_alter_conversacionparticipante_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='conversacionparticipante',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='propuestaencuentro',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='puntoencuentro',
            options={'managed': False},
        ),
    ]
