# Generated by Django 5.2.6 on 2025-11-07 02:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0011_alter_conversacionparticipante_options_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='propuestaencuentro',
            table='market_propuestaencuentro',
        ),
        migrations.AlterModelTable(
            name='puntoencuentro',
            table='market_punto_encuentro',
        ),
    ]
